In [3]:
import cv2
import numpy as np

src_zeros = np.zeros([3,3],dtype=np.uint8)
src_ones = np.ones([3,3],dtype=np.uint8)
src_range = np.arange(9,dtype=np.uint8).reshape(3,3)

print(src_zeros)
print(src_ones)
print(src_range)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import cv2
dst = cv2.bitwise_and(src_ones,src_range, mask=None)
print(dst)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


In [9]:
import numpy as np
line =np.array([[3,-1],[1,1]],dtype = np.float32)
answer = np.array([3,2],dtype=np.float32)

success, lu = cv2.solve(line,answer,cv2.DECOMP_LU)
print(lu)
print(success)

[[1.25]
 [0.75]]
True
